name: tests

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    env:
      SLOW_TESTS: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt update &&
          sudo apt install --yes xvfb python3-tk
      - name: Install pip dependencies
        run: pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          touch ~/.Xauthority  # workaround for https://github.com/python-xlib/python-xlib/issues/66
          coverage run -m xmlrunner -v --output-file test_output/test_results.xml
          coverage report
          coverage xml
      - name: Publish Code Coverage Results
        uses: codecov/codecov-action@v2
        with:
          files: ./test_output/coverage.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test_output/test_results.xml
      - name: Archive all collected test results
        uses: actions/upload-artifact@v2
        with:
          name: test_output
          path: test_output/